project:
  type: website
  output-dir: docs

website:
  title: "Will St. John"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research

format:
  html:
    theme:
      dark: [cosmo, dark.scss]
      light: [cosmo, light.scss]
      
    css: styles.css
    toc: true



