project:
  type: website
  output-dir: docs

website:
  title: "Will St. John"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - text: Courses
        menu:
          - href: courses/honors/index.qmd
            text: Honors
          - href: courses/astrophysics/index.qmd
            text: Astrophysics
          - href: courses/ML/index.qmd
            text: Machine Learning
          - href: courses/topology/index.qmd
            text: Topology
          - href: courses/quantum/index.qmd
            text: Quantum
          - href: courses/compGeom/index.qmd
            text: Computational Geometry

format:
  html:
    theme:
      light: [cosmo, light.scss]
      dark: [cosmo, dark.scss]
      
    css: styles.css
    toc: true



