---
title: "Astrophysics Exam 2 Revision"
author: "Will St. John"
---

# Problem 1

a) What is convection?
b) In our current models of stellar structure, how is it decided whether a particular zone within a stellar interior is convective or not? Be as descriptive and quantitative as possible.
c) Where is convection important in the Sun, and why?
d) Where is convection important in higher mass stars, and why?

> **Original Answer (7/10)**:
>
> a) Convection is mass flow of particles that travel in a group at approximately the same speed.
> b) Temperature gradient. If the actual temperature gradient is greater than the adiabatic temperature gradient, then convection will occur.
> c) Convection happens in the outer most region from $R=0.714 R_\odot$ to $1R_\odot$. This region is imporant because convection causes B-field lines and sunspots and the differential rotation causes these B-field lines to flip every 11 years. We primary care about convection because it influenced B-field lines which can cause solar activity that directly affect Earth.
> d) Convection is important everywhere in higher mass stars becase they are so hot that they need convection to transport energy. We want to understand convection in stars because they produce heavy elements and the ISM.
>
> **Revised Answer (10/10)**: Other than part c), I would reword my answers slightly to the following:
>  
> a) Convection describes the energy transport process when energy is moved in large flows or currents.
> b) Our current models for stellar evolution predict a zone will be convective if the temperature gradient in that region is greater than the adiabatic temperature gradient.
> c) Same as original answer.
> d) Higher mass stars undergo the CNO cycles which, due to the cycle's large temperature dependence, encourages energy to leave the core via convection. This convection allows higher mass stars to be more efficient mixers of elements, prolonging their lives on the main sequence.
>
> Given that most of my final answers are rewordings of my original, I would give myself a 7/10 for my original work on this problem.


# Problem 2
Consider the dense core of a molecular cloud. This inner core has an average mass density of $1.6\times10^{-17}$ kg m$^{-3}$, a total mass of 11.2 Solar masses, and a mean molecular weight of $\mu = 2.1$. Assume the temperature is 10 K.

a) What is the free-fall timescale in years?
b) What is the Jeans' length in pc?
c) What is the Jeans' Mass in solar masses?
d) What is the radius of the cloud?
e) Based on these calculations, what do you expect to hapen to this cloud? E.g., is it stable or unstable, and what does that mean?

> **Original Answer (7/10)**:
>
> a) $t_{ff} = \left(\frac{4\pi}{32}\frac{1}{G\rho_0}\right)^{1/2} = \left[(0.2945)(9.366\cdot10^{26})\right]^{1/2} = 1.66\cdot10^{13}$ s $\longrightarrow$ to yr
> b) $R_J = \left(\frac{15kT}{4\pi G\mu m_H \rho_0}\right)^{1/2} = \left(\frac{2.07\cdot10^{-21}}{4.705\cdot10^{-53}}\right) = 6.6329\cdot10^{15}$ m $\longrightarrow$ to pc
> c) $M_J = \left(\frac{5kT}{G\mu m_H}\right)^{3/2}\left(\frac{3}{4\pi\rho_0}\right)^{1/2} = $
> d) $R = \left(\frac{3M}{4\pi\rho_0}\right)^{1/3}$
> e) collapse if $M > M_J$
>
> **Revised Answer (10/10)**: For most of the calculations on this exam, I was able to set up the problem and plug in the numbers, but I was not able to solve for the final value. Specifically for parts a) and b) of this question, however, I was able to derive an equivalent final value, just not converted to the final units asked for in the problem. The code chunks below complete the calculations I was not able to accomplish during the exam. Given that the cloud mass is larger than the Jeans' Mass and the clouds length is larger than Jeans' length, we expect this cloud to collapse.
> 
```{python}
import astropy.units as u
import astropy.constants as c
import numpy as np

# define given values
rho0 = 1.6E-17 * u.kg / u.m ** 3
M = 11.2 * u.M_sun
mu = 2.1
T = 10 * u.K
m_H = c.m_p

# a)
t_ff = (3 * np.pi / (32 * c.G * rho0)) ** 0.5
print(f"free-fall timescale: {t_ff.to(u.yr):.2e}")

# b)
R_J = (15 *c.k_B * T / (4 * np.pi * c.G * mu * m_H * rho0)) ** 0.5
print(f"Jeans' length: {R_J.to(u.pc):.2f}")

# c)
M_J = (5 * c.k_B * T / (c.G * mu * m_H)) ** (3/2) * (3 / (4 * np.pi * rho0)) ** 0.5
print(f"Jeans' mass: {M_J.to(u.M_sun):.2f}")

# d)
R = (3 * M / (4 * np.pi * rho0)) ** (1/3)
print(f"Radius of cloud: {R.to(u.pc):.2f}")
```
>
> I knew what equations to use for my original answers and I was able to plug in the right values to derive the correct result. The only things I wasn't able to accomplish on this problem was calculating parts c), d), and e), and converting units. If I had more time/was more proficient at typing values into the handheld calculator, I would have been able to complete this problem as I understood the process behind each question, thus, I would give myself a 7/10 for my original answer.

# Problem 3
The plot below shows the Jeans stability criterion, with mass plotted as a function of density. Two individula clouds, labeled "Cloud A" and "Cloud B", are shown. You man assume that each cloud has the same temperature and the same composition.

a) Identify if one, both, or neither of clouds would be considered stable against gravitational collapse. Explain your answer.
b) What is the radius of cloud A?
c) What is the radius of cloud B?

> **Original Answer (8/10)**:
>
> a) A cloud collapses if $M_c > M_J$, thus we expect the green cloud (Cloud A) to collapse while the blue dot (Cloud B) would not.
> b) $R_A = \left(\frac{3M}{4\pi\rho}\right)^{1/3} = \left(\frac{3\cdot13\cdot1.99\cdot10^{30}}{4\pi\cdot10^{-17}}\right)^{1/3} = 4.98\cdot10^{15}$ m
> c) $R_B = \left(\frac{3M}{4\pi\rho}\right)^{1/3} = \left(\frac{3\cdot9\cdot1.99\cdot10^{30}}{4\pi\cdot5\cdot10^{-17}}\right)^{1/3} = 4.406\cdot10^{15}$ m
> 
> **Revised Answer (10/10)**: My original answer for a) is correct. If the purple line shows the Jeans stability criterion with mass on the y axis, then any points that fall below the line would have masses less than the Jeans mass, and therefore be stable from collapse. If any points were above the line, then the cloud would have a mass greater than the Jeans mass and collapse as a result. In other words, Cloud A would collapse and Cloud B would not.
> 
> As the code chunk below shows, I had the right order of magnitude but slightly different answers for part b) and c). This discrepancy is due to a calculation error in my original work: I switched the masses of the clouds and incorrectly estimated the densities from the graph.

```{python}
# define values given in problem
M_A = 9 * u.M_sun
rhoA = 6E-17 * u.kg / u.m ** 3
M_B = 13 * u.M_sun
rhoB = 2E-17 * u.kg / u.m ** 3

# b)
R_A = (3 * M_A / (4 * np.pi * rhoA)) ** (1/3)
print(f"Radius of Cloud A: {R_A.to(u.m):.2e}")

# c)
R_B = (3 * M_B / (4 * np.pi * rhoB)) ** (1/3)
print(f"Radius of Cloud B: {R_B.to(u.m):.2e}")
```
>
> Since my errors for parts b) and c) were only computation errors, I would give myself an 8/10 for my original work.


# Problem 4
A Source has a luminosity of $6\times10^{13}$ watts. You observe this source from a distance of 6.25 km. The intervening material has a density of 0.012 kg per cubic meter and an opacity of 0.02 m$^2$ kg$^{-1}$.

a) What is the optical depth of the medium?
b) In the absence of extinction, what is the measured flux in W/m$^2$?
c) In the presence of extinction, what is the measured flux in W/m$^2$?

> **Original Answer (7/10)**:
>
> a) $\tau_\lambda = \int_0^s\kappa\rho ds = \kappa\rho s = (0.02)(0.012)(6.25\cdot10^3) = $
> b) $F = \frac{L}{4 \pi r^2} = \frac{6\cdot10^{13}}{4\pi(6.25\cdot10^3)^2} = $
> c) $m_\lambda - m_{\lambda,0} = 1.086 \tau_\lambda = -2.5\log_{10}\left(\frac{F}{F_{\lambda,0}}\right)$ solve for F?
>
> **Revised Answer (10/10)**: I set up the problem correctly for parts a) and b) in my original answer, and I was going down the right path in part c), however, I did not calculate a final answer. The code chunk below calculates the final answers. Note that for part c), we had to rearrange
>
> $$1.086 \tau_\lambda = -2.5\log_{10}\left(\frac{F}{F_{\lambda,0}}\right)$$
>
> to solve for $F$. Another valid way to estimate $F$ is under the relation
>
> $$I = I_0 e^{-\tau}$$
>
> and substituting in $F$ and $F_0$ for $I$ and $I_0$, respectively.

```{python}
# define variables
L = 6E13 * u.W
d = 6.25 * u.km
rho = 0.012 * u.kg / u.m ** 3
kappa = 0.02 * u.m ** 2 / u.kg

# a)
tau_l = kappa * rho * d
print(f"optical depth: {tau_l.to(u.dimensionless_unscaled)}")

# b)
F_0 = L / (4 * np.pi * d ** 2)
print(f"flux (no extinction): {F_0.to(u.W / u.m ** 2):.2e}")

# c)
F = F_0 * 10 ** (1.086 * tau_l / -2.5)
F_alt = F_0 * np.exp(-tau_l)
print(f"flux (with extinction): {F.to(u.W / u.m ** 2):.2e}")
print(f"flux (with extinction, alt. method): {F_alt:.2e}")
```
>
> Because I had the correct process for the majority of the problems, and I just didn't have enough time to enter the final numbers into the calculator, I would give myself a 7/10 for my original answer.


# Problem 5
The plot below shows extinction in magnitudes as a function of wavelength along the sightlines to three objects, labeled "A", "B", and "C". The individual points represent individual measurements in specific filters; this is real data and there is uncertainty in the measurements. Assume distances to each object as follows: $D_A = 611$ kpc; $D_B = 6.2$ Mpc; $D_C = 2.35$ Mpc.

a) Which sightline has the largest extinction?
b) Which sightline experiences the smallest extinction?
c) A star with absolute magnitude -2.47 is observed at 800 nm in each of the objects. What are the apparent magnitudes of each star, "A", "B", "C"?

> **Original Answer (8/10)**:
>
> a) C has the highest extinction across all $\lambda$
> b) A has the smallest extinction across all $\lambda$
> c) Would need to calculate $m_\lambda$ and $m_\lambda - m_{\lambda,0} = A_\lambda = 1.068 \tau_\lambda$, so would either need to know unextinct values ($m_{\lambda,0}$) or $\tau_\lambda\implies \kappa, \rho$ 
>
> **Revised Answer (10/10)**: The extiction of an object is $A_\lambda$, thus, my answers for a) and b) still hold; C has the highest extiction ($A_\lambda$) across all wavelengths and A has the lowest extinction across all wavelengths. The first sentence of part c) was commented out when the test was passed out, so the code chunk below calculates the apparent magnitudes for the three stars. Note that the $A_\lambda$ values were estimated from the plot at $\lambda = 800 \text{ nm } = 0.8 \text{ micron}$.
>
```{python}
# define variables
D_A = 611 * u.kpc
D_B = 6.2 * u.Mpc
D_C = 2.35 * u.Mpc
A_A = 0.6
A_B = 1.6
A_C = 2.4
M = -2.47

# c)
m_A = M + 5 * np.log10(D_A.to(u.pc).value) - 5 + A_A
m_B = M + 5 * np.log10(D_B.to(u.pc).value) - 5 + A_B
m_C = M + 5 * np.log10(D_C.to(u.pc).value) - 5 + A_C
print(f"m_A: {m_A:.2f}")
print(f"m_B: {m_B:.2f}")
print(f"m_C: {m_C:.2f}")
```
>
> Given that we were missing some of the question in the exam, I would give myself a 8/10 for the original version of this problem as I knew we were missing something, but I didn't mention we were missing the absolute magnitude directly.

# Problem 6
What is something in 2025 that you are proud of?

> **Original/Revised Answer**: I published a Research Note to the AAS.


# Problem 7
Consider the following plot, which shows the hypothetical Macalester initial mass function (IMF). This differs in significant ways from the Salpeter IMF in that the Macalester IMF has different slopes in different mass ranges; the different colors label the different slopes, and the vertical dashed lines show the positions of the changes. In contrast, the Salpeter IMF has a constant $\gamma = -2.35$ over all masses. Compare these IMFs under the assumption that the star-forming environments are identical.

a) Which IMF predicts an higher efficiency of formation of the most very massive stars?
b) Which IMF results in the production of more low-mass stars?
c) Describe the pros and cons of each model with respect to their potential of accurately predicting the distribution of stars formed when a modelular cloud collapses.

> **Original Answer (9/10)**:
>
> a) Given the Salpeter intersects at red-blue region, the Mac IMF produces a higher efficiency of more massive stars
> b) For the same rational as above, the Salpeter IMF predicts more low mass stars
> c) Both are potentially valid IMFs, but the Macalester one might be more applicable due to its piecewise nature.
>
> **Revised Answer (10/10)**: I would maintain the same answers for parts a) and b), but I would revise my answer for part c) to the following: Both models could potentially describe the number of stars found across the range of stellar masses, but, as parts a) and b) have shown, it is possible that either model over/underestimates the production of low/high-mass stars. Additionally, the piecewise nature of the Macalester IMF might be more applicable, especially given the new papers (shown in class) that have captured the turnover of the IMF.
>
> I would give my original answer a 9/10, as I feel I should have elaborated more on part c).


# Problem 8
Consider an individual radial zone of a 1 Solar mass stellar model (i.e., a model of the Sun). This zone covers a narrow range of radii and thus enables a plane-parallel approximation of physical parameters. The mass contained in this zone is 0.9% of the total mass and the position of the zone is at 61% of the toal radius. Adopt a mean molecular weight that is appropriate for ionized gas, $\mu = 0.754$. Assume that convection is the primary method of energy transport, and that the gas can be adequately described by the ideal gas law. What is the temperature gradient across this region, in units of Kelvin per meter?

> **Original Answer (7/10)**: 
> 
> $$\frac{dT}{dr} = -\left(1 - \frac{1}{\gamma}\right)\frac{\mu m_H}{k}\frac{GM_r}{r^2} = -(1-\frac{1}{5/3})\frac{(0.754)(1.67\cdot10^{-27}\text{ kg})}{(1.38\cdot10^{-23}\text{ J/K})}(6.67\cdot10^{-11}\frac{\text{Nm}^2}{\text{kg}^2})\cdot\left(\frac{0.9\cdot1.99\cdot10^{30}\text{ kg}}{(0.61\cdot6.95\cdot10^{8}\text{ m})^2}\right)$$
>
> **Revised Answer (10/10)**: I wrote down the equation and substituted in the given values in my original answer, but I didn't have enough time to simplify to a final answer, like I do in the code chunk below. For this reason, I would give myself a 7/10 for my original answer.

```{python}
# define variables
M_r = 0.9 * u.M_sun
R = 0.61 * u.R_sun
mu = 0.754
gamma = 5/3

# calculate convection temperature gradient
tempgrad = -(1 - 1/gamma) * (mu * m_H * c.G * M_r) / (c.k_B * R ** 2)
print(f"temperature gradient: {tempgrad.to(u.K / u.m):.4f}")
```

# Problem 9

a) Describe the different modes of fusion that occur in stars on the main sequence.
b) Which mode of fusion is more important in higher mass stars than in lower mass stars, and why?
c) The Sun is believed to be more luminous now that when it first arrrived on the main sequence. Explain why.

> **Original Answer (8/10)**:
>
> a) In MS stars, hydrogen is fusing to helium in the core, but the process by which it happens could differ depending on the mass of the star. For moderate to low mass stars, like the Sun, the core is fusing through radiation, while in high and low mass stars, the core is fusing through convections.
> b) Higher mass stars have fusion through convection in their core because they are so much more hotter, so the most efficient energy transport mechanism is through convection. Convection allows for the CNO cycle to take place as well, which can help produce helium more efficiently than through the radiative p-p chain.
> c) The Sun is more luminous than when it first arrived on the MS because its composition has changed. He is now the dominant element in the core, which means the core's mean molecular weight has increased, causing contraction and subsequent temperature increase.
>
> **Revised Answer (10/10)**: I would revise my answers to the following.
>
> a) In MS stars, hydrogen is fusing to helium in the core, but the process by which fusion occurs differs depending on the mass of the star. For moderate to low mass stars, like the Sun, the core is fusing through radiation, while in high and very low mass stars, the core is fusing through convections.
> b) Higher mass stars have fusion through convection in their core because they have extremely high temperatures, which causes the more efficient energy transport mechanism, convection, to take over. Convection allows for the CNO cycle to take place as well, which can help produce helium more efficiently than through the radiative p-p chain at the high mass star's given temperature. Additionally, convection allows a more efficient mixing of elements in the star, which extends the lifetime of the star as it is able to use hydrogen and helium that are not just in the nearest regions to the core.
> c) The Sun is more luminous than when it first arrived on the MS because its composition has changed. He is now the dominant element in the core, which means the core's mean molecular weight has increased, causing contraction and subsequent temperature increase.
>
> Given my revisions primarily elaborated on ideas already expressed in my original answer, I would give my original answers an 8/10.



# Problem 10
Consider the evolutionary path shown in the HR diagram below.

a) What mass star is shown in this evolutionary tract?
b) Describe what is happening between each letter.

> **Original Answer (10/10)**: 
>
> a) Given the slope of the horizontal branch, this is likely a lower mass star $\sim1M_\odot$.
> b) (a) Star is in MS, burning H to He. (b)  H core exhausted, H-shell stars to burn, start of subgiant branch: He core contracts, core temp increases, envelope expands, $T_{eff}$ decreases, He ash falls on core, core contracts, cycle repeats till S-C limit. (c) S-C limit reached, start of red giant branch, convection begins near surface growing inward, we get our first dredge up of materials (can see $^3_2$He and $^14_7$N while C and lithium move in). (d) He core flash: He core has become more $e^-$ degenerate, neutrino loss in core causes temperature inversion, $3\alpha$ process starts and is nearly explosive, He shell activated, core joins, temp inversion removed and interior is as luminous as galaxy for short time, but outer layers absorb energy. (e) After He core flash, star temp is increasing and luminosity decreasing, and we begin the horizontal branch, blueward. Envelope is contracting and we have convection in core and envelope. Blue motion is analogous to H fusion in MS, just with He. At bluest point, $\mu$ is increasing and the core contracts, envelope exands and cools, moving redward. Eventually He core is exhausted and CO core continues to contract. He shell narrows, temperature increases, layers expand, cooling (pulsations). H shell turns off temporarily, CO core contracts, neutrino production increases, core temperature decreases. (e-to-f) We get to early asymptotic giant branch: He shell burns like H-shell in RGB and the envelope absorbs initially, then convection causes a second dredge up. The H shell turns back on, He shell turns off/on again and again through similar process to He core flash (i.e. ash from H shell) and $e^-$ degenerate core causes based for shell to expand and repeat the process in the thermal pulse AGB phase. (f-to-g) Mass loss prevents collapse of star, core makes additional elements, we can get superwind, eventually we loose enough mass that the envelope form superwind is optically thin and the remnant degenerate core is revealed (but that isn't show in the plot).
>
> **Revised Answer (10/10)**: After checking in the book, I think I could have revised by answer to a) to say something about it being a 1-5$M_\odot$ star, but that is just extra clarification that isn't too necessary. For that reason, I would give myself a 10/10 for my original answer to this problem.


# Problem 11
How would the evolutionary tract change if the star was 5-10 times more massive than the star shown in the HR diagram above? Provide as much detail as possible, again commenting on what would be similar or different between each letter.

> **Original Answer (7/10)**: If stars were more massive, we would expect no He core flash, and the horizontal branch would appear more horizontal. We'd also get a 3rd dredge up in the thermal pulse AGB and a more flat subgiant branch.
>
> **Revised Answer (10/10)**: Given that we infer the star to be around 1 solar mass, this question is asking about the stellar evolution of a ~5-10 solar mass star. I would argue that my original answers hold, but they only touched on the differences as the rest of the evolution of a ~5-10 solar mass star is quite similar to that of a 1 solar mass star. Directly copying the description of stellar evolution from Problem 10 to replace a few phrases was too time consuming at the time of the exam, but I do so now below.
>
> (a) Star is in MS, burning H to He. (b)  H core exhausted, H-shell stars to burn, start of subgiant branch: He core contracts, core temp increases, envelope expands, $T_{eff}$ decreases, He ash falls on core, core contracts, cycle repeats till S-C limit. (c) S-C limit reached, start of red giant branch, convection begins near surface growing inward, we get our first dredge up of materials (can see $^3_2$He and $^14_7$N while C and lithium move in). (d-to-e) No He core flash, rather a more He core brning. Star temp is increasing and luminosity decreasing, and we begin the horizontal branch, blueward. Envelope is contracting and we have convection in core and envelope. Blue motion is analogous to H fusion in MS, just with He. At bluest point, $\mu$ is increasing and the core contracts, envelope exands and cools, moving redward. Eventually He core is exhausted and CO core continues to contract. He shell narrows, temperature increases, layers expand, cooling (pulsations). H shell turns off temporarily, CO core contracts, neutrino production increases, core temperature decreases. (e-to-f) We get to early asymptotic giant branch: He shell burns like H-shell in RGB and the envelope absorbs initially, then convection causes a second dredge up. The H shell turns back on, He shell turns off/on again and again through similar process to He core flash (i.e. ash from H shell) and $e^-$ degenerate core causes based for shell to expand and repeat the process in the thermal pulse AGB phase. Convection zones between He shell and H shell combine with convection zones in the envelope and we get our third dredge up, where we are able to see carbon spectroscopically, known as "carbon stars". (f-to-g) Mass loss prevents collapse of star, core makes additional elements, we can get superwind, eventually we loose enough mass that the envelope form superwind is optically thin and the remnant degenerate core is revealed (but that isn't show in the plot).

# Reflection

1) What did you feel the most and least confident about going into the exam?

> **Answer**: After the first exam, I felt most confident about the style of questions to expect and my ability to cover as many questions as possible in the time allowed. I think I did a great job with that, as I recognized question 10 as requiring a lot of writting and thus devoted most of my intial work to writing my answer out. I also felt confident in my ability to understand extinction as I spent an independent study with Jay on the topic.
>
> I felt least confident in my knowledge of the Sun. Namely, I was unsure what quantitative questions could be asked on the Sun, so I was thinking questions on the topic would be more qualitiative so I refrained from putting much information on the Sun on my equation sheet.

2) What did "grading"/"correcting" your exam help you to understand better?

> **Answer**: Most directly, I think grading my exam helped me understand the answers to all the questions I didn't have time to calculate, and specifically part c) of Problem 5 which I didn't fully understand when I took the exam. More indirectly, I think grading my exam helped me solidify my understanding of the Jeans criterion and the initial mass function. As with the last exam, I also solidified my understanding that I am more proficient at calculations with Python than handheld calculators. 

1) What topics from the second unit do you feel like you still have the most room for improvement?

> **Answer**: I think I have the most room for improvement on the physics during the stages of stellar evolution. My equation sheet had the entire stellar evolution process written out for each stage and a corresponding stellar evolution HR diagram for both low and moderate mass stars. The information for the unit is extremely dense and understanding it is vital because it quite literally describes how stars evolve, and a better understanding of how stars evolves improves our understanding of galaxies and larger structures. All of that is to say, I found remembering concepts from the stellar evolution section difficult because of how dense the section is.

4) If 10 pts per problem (except problem 6), what would your original grade be versus the version you’re turning in now?

> **Answer**: Excluding problem 6, I would have received a 78/100. With revisions, I believe I have corrected my exam to around 100/100.


