---
title: PHYS 481 - Quantum Mechanics
subtitle: Assignment 03
author: Will St. John
date: 10/15/2025
---

# Problem 1
In a harmonic oscillator a coherent state $\psi_{\alpha}(x)$ is defined as follows: When acted on by the lowering operator $\hat{a}_-$, we get the wave function back times a constant:

$$\hat{a}_- \psi_\alpha(x) = \alpha \psi_{\alpha}(x)$$

or in linear algebra language, $\psi_{\alpha}(x)$ is an eigenvector of $\hat{a}_-$ with eigenvalue $\alpha$. Different coherent states have different values of $\alpha$. Do *not* in general assume that the constant $\alpha$ is real. *(Coherent states have many applications in atomic, molecular, and optical physics. For instance, lasers and Bose-Einstein condensates are examples of coherent states.)*

a) Show that for any square-integrable functions $f(x)$ and $g(x)$ $$\int_{-\infty}^{\infty}f^*(x)(\hat{a}_\pm g(x))dx = \int_{\infty}^{\infty}(\hat{a}_\mp f(x))^*g(x)dx$$
b) Use Eq. (2) along with the eigenvector equation (1) to evaluation $\left<x\right>$ and $\left<p\right>$ for the coherent state wave function $\psi_\alpha$ in terms of $\alpha$ and constants. You may assume $\psi_{\alpha}(x)$ is normalized. (Hint: how can $\hat{x}$ and $\hat{p}$ be written in terms of $\hat{a}_+$ and $\hat{a}_-$?)
c) Is the ground state $\chi_0(x)$ of the harmonic oscillator a coherent state? What is the value of $\alpha$?
d) Any wave function of the harmonic oscillator can be expressed as a linear combination of stationary states $\chi_n(x)$ of the harmonic oscillator. Assume therefore that $$\displaystyle\psi_\alpha(x) = \sum_{n=0}^{\infty}c_n\chi_n(x),$$ and show that the $c_n$ are given by $$c_n = \frac{\alpha^{n}}{\sqrt{n!}}c_0.$$ (Hint: Operate with $\hat{a}_-$ on Eq. (3).)
e) Another interesting property of coherent states is how their expectation values evolve in time. Recall that stationary states have time-independent expectation values; coherent states are different. Assume that $\Psi_\alpha(x, t=0) = \psi_\alpha(x)$ and show that $\Psi_\alpha(x, t)$ is still a coherent state - that is, show it satisfies $$\hat{a}_- \Psi_\alpha(x,t) = \alpha(t) \Psi_{\alpha}(x,t)$$. What is $\alpha(t)$ in terms of $\alpha$ and other quantities?
f) In this part, for simplicity assume $\alpha$ is real (but $\alpha(t)$ might not be real). Take the results for $\left<x\right>$ and $\left<p\right>$ from part b) and put the value of $\alpha(t)$ into them to find $\left<x\right>(t)$ and $\left<p\right>(t)$ for $\Psi_\alpha(x,t)$$. How does the result compare to the classical motion of a particle in a harmonic oscillator?

> **Response**: Before we start, rewriting the following terms and simplications will make our calculations easier throughout the problem.
>
> $$\begin{align} \hat{p} &= -i\hbar \frac{d}{dx} \\ \\ \hat{a}_\pm &= \frac{1}{\sqrt{2\hbar m \omega}}\left(\mp i\hat{p} + m\omega\hat{x}\right) \\ \hat{a}_+ &= -\sqrt{\frac{\hbar}{2m\omega}}\frac{d}{dx} + \sqrt{\frac{m\omega}{2\hbar}}x \\ &= -A\frac{d}{dx} + Bx,\quad A=\sqrt{\frac{\hbar}{2m\omega}},\; B=\sqrt{\frac{m\omega}{2\hbar}}\\ \hat{a}_- &= A\frac{d}{dx} +  Bx\end{align}$$
>
> For part a) (just using $\hat{a}_+$)
>
> $$\begin{align}\int_{-\infty}^{\infty}f^*(x)(\hat{a}_+ g(x))dx &= \int_{-\infty}^{\infty}f^*(x)\left(\left(-A\frac{d}{dx} + Bx\right) g(x)\right)dx \\ &= -A\int_{-\infty}^{\infty}f^*(x)g'(x)dx + B\int_{-\infty}^{\infty}f^*(x)xg(x) dx \\ &= -A\left[-\int_{-\infty}^{\infty}(f^*(x))'g(x)dx + f^*(x)g(x)\Big|_{-\infty}^{\infty}\right] + B\int_{-\infty}^{\infty}f^*(x)xg(x) dx \\ &= A\int_{-\infty}^{\infty}(f^*(x))'g(x)dx + B\int_{-\infty}^{\infty}f^*(x)xg(x) dx \\ &= \int_{-\infty}^{\infty}\left[A(f^*(x))' + Bf^*(x)x\right]gdx \\ &= \int_{-\infty}^{\infty}\left[A\frac{d}{dx}f^*(x) + Bxf^*(x)\right]gdx \\ &= \int_{-\infty}^{\infty}\left(A\frac{d}{dx}+ Bx\right)f^*(x)g(x) dx \\ &= \int_{-\infty}^{\infty}\hat{a}_-f^*(x)g(x) dx \\ &= \int_{\infty}^{\infty}(\hat{a}_- f(x))^*g(x)dx \end{align}$$
>
> Note that we can do the same process starting with $\hat{a}_-$, the only difference is that every $A$ will have a $-$ in front of it, but the end result will still satisfy the relationship.
>
> For part b), note that we can rewrite $\hat{x}$ and $\hat{p}$ as $$\hat{x} =\sqrt{\frac{\hbar}{2m\omega}}\left(\hat{a}_+ + \hat{a}_-\right) ,\quad \hat{p} = i\sqrt{\frac{\hbar m \omega}{2}}\left(\hat{a}_+ - \hat{a}_-\right)$$
> 
> It follows that
>
> $$\begin{align} \left<x\right> &= \int_{-\infty}^{\infty}\psi_\alpha^*\left[\sqrt{\frac{\hbar}{2m\omega}}\left(\hat{a}_+ + \hat{a}_-\right)\right]\psi_\alpha dx \\ &= \sqrt{\frac{\hbar}{2m\omega}}\left(\int_{-\infty}^{\infty}\psi_\alpha^*\hat{a}_+\psi_\alpha dx + \int_{-\infty}^{\infty}\psi_\alpha^*\hat{a}_-\psi_\alpha dx\right) \\ &= \sqrt{\frac{\hbar}{2m\omega}}\left(\int_{-\infty}^{\infty}(\hat{a}_-\psi_\alpha)^*\psi_\alpha dx + \alpha\int_{-\infty}^{\infty}\psi_\alpha^*\psi_\alpha dx\right) \\ &= \sqrt{\frac{\hbar}{2m\omega}}\left(\alpha^* + \alpha\right) \\ \\ \left<p\right> &= \int_{-\infty}^{\infty}\psi_\alpha^*\left[i\sqrt{\frac{\hbar m \omega}{2}}\left(\hat{a}_+ - \hat{a}_-\right)\right]\psi_\alpha dx \\ &= i\sqrt{\frac{\hbar m \omega}{2}}\left(\int_{-\infty}^{\infty}\psi_\alpha^*\hat{a}_+\psi_\alpha dx - \int_{-\infty}^{\infty}\psi_\alpha^*\hat{a}_-\psi_\alpha dx\right) \\ &= i\sqrt{\frac{\hbar m \omega}{2}}\left(\int_{-\infty}^{\infty}(\hat{a}_-\psi_\alpha)^*\psi_\alpha dx - \alpha\int_{-\infty}^{\infty}\psi_\alpha^*\psi_\alpha dx\right) \\ &= i\sqrt{\frac{\hbar m \omega}{2}}(\alpha^* - \alpha)\end{align}$$
>
> For part c), if we apply $\hat{a}_-$ to $\psi_0$ and get a constant and $\psi_0$ back out, then the ground state is a coherent state.
>
> $$\begin{align}\psi_0 &= \left(\frac{m\omega}{\pi\hbar}\right)^{1/4}e^{-\frac{m\omega}{2\hbar}x^2} \\ &= \left(\frac{2}{\pi}\right)^{1/4}B^{1/2}e^{-B^2x^2} \\ \\ \hat{a}_-\psi_0 &= \left(A\frac{d}{dx}+ Bx\right)\left(\frac{2}{\pi}\right)^{1/4}B^{1/2}e^{-B^2x^2} \\ &= A\frac{d}{dx}\left(\frac{2}{\pi}\right)^{1/4}B^{1/2}e^{-B^2x^2} + Bx\left(\frac{2}{\pi}\right)^{1/4}B^{1/2}e^{-B^2x^2} \\ &= \underbrace{\left(-2AB^2x + Bx\right)}_{\alpha}\underbrace{\left(\frac{2}{\pi}\right)^{1/4}B^{1/2}e^{-B^2x^2}}_{\psi_0} \\ \\ \alpha &= B(1-2AB)x,\quad A = \frac{1}{2B} \\ \alpha &= 0\end{align}$$
>
> Noting that $A = \frac{1}{2B}$, we can see that in order $\alpha$ to be constant for all $x$, $\alpha$ must be 0. Thus, the ground state is a coherent state if $\alpha = 0$.
>
> For part d), we can derive the relationship by exploring what happens when $\hat{a}_-$ acts of the sum.
>
> $$\begin{align} \psi_\alpha &= \sum_{n=0}^{\infty} c_n \chi_n \\ \hat{a}_-\psi_\alpha &= \sum_{n=0}^{\infty} c_n \hat{a}_-\chi_n \\ \alpha\psi_n&= \sum_{n=0}^{\infty} c_n\sqrt{n}\chi_{n-1} \\ \alpha\psi_n &= \sum_{n=0}^{\infty}\alpha c_n\chi_n \\ \sum_{n=0}^{\infty}c_n\sqrt{n}\chi_{n-1} &= \sum_{n=0}^{\infty}\alpha c_n\chi_n \\ (n=1)&\quad \sum_{n=1}^{\infty}c_{n+1}\sqrt{n+1}\chi_n \\ \\ c_{n+1} \sqrt{n+1} &= \alpha c_n \\ c_{n+1} &= \frac{\alpha}{\sqrt{n+1}}c_n \\ c_n &= \frac{\alpha^n}{\sqrt{n!}}c_0 \end{align}$$
>
> For part e), the calulcation below derives $\alpha(t) = \alpha e^{-i\omega t}$
>
> $$\begin{align} \hat{a}_-\Psi_\alpha &= \sum_{n=0}^{\infty}c_n \hat{a}_-\chi_n e^{-iE_nt/\hbar} \\ &= \sum_{n=0}^{\infty}c_n \sqrt{n}\chi_{n-1} e^{-iE_nt/\hbar} \\ (\text{shift to }n+1) &= \sum_{n=0}^{\infty}c_{n+1} \sqrt{n+1}\chi_{n} e^{-iE_{n+1}t/\hbar} \\ &= \sum_{n=0}^{\infty}\alpha c_{n}\chi_{n} e^{-i(E_n + \hbar\omega)t/\hbar} \\ &= \underbrace{\alpha e^{-i\omega t}}_{\alpha(t)}\underbrace{\sum_{n=0}^{\infty}c_n\chi_n e^{-i E_n t/\hbar}}_{\Psi_\alpha}\end{align}$$
>
> For part f), combining the results from part b) with $\alpha(t)$ from e) (and only considering the real part), we get the following for $\left<x\right>$ and $\left<p\right>$
>
> $$\begin{align}\left<x\right> &= \sqrt{\frac{\hbar}{2m \omega}}\left(\alpha e^{i\omega t} + \alpha e^{-i\omega t}\right) \\ &= \sqrt{\frac{\hbar}{2m \omega}}\alpha\left(\cos\omega t + i \sin\omega t + \cos(-\omega t) + i\sin(-\omega t)\right) \\ &= 2\alpha\sqrt{\frac{\hbar}{2m \omega}}\cos\omega t \\ &= \alpha\sqrt{\frac{2\hbar}{m \omega}}\cos\omega t \\ \\ \left<p\right> &= i\sqrt{\frac{\hbar m \omega}{2}}\left(\alpha e^{i\omega t} - \alpha e^{-i\omega t}\right) \\ &= i\alpha\sqrt{\frac{\hbar m \omega}{2}}\left(\cos\omega t + i\sin\omega t - \cos(-\omega t) - i \sin(-\omega t)\right) \\ &= i\alpha\sqrt{\frac{\hbar m \omega}{2}}\left(\cos\omega t + i\sin\omega t - \cos\omega t + i \sin\omega t\right) \\ &= -\alpha\sqrt{2\hbar m \omega}\sin\omega t \end{align}$$
>
> For comparison, classically, we get
>
> $$\begin{align} x &= A \cos \omega t \\ p &= m \frac{dx}{dt} &= -m\omega A\sin\omega t\end{align}$$
>
> Look's pretty similar!

# Problem 2
A system is initially in the state $$\Psi(x, t=0) = \frac{1}{\sqrt{7}}\left(\sqrt{2}\chi_1(x) + \sqrt{3}\chi_2(x) - i\chi_3(x) + \chi_4(x)\right)$$ where $\chi_n(x)$ are eigenstates of the systems's Hamiltonian such that $\hat{H}\chi_n(x) = n^2E_0\chi_n(x)$

a) Is $\Psi(x,t)$ normalized for $t>0$?
b) If the energy of state is measured, what values will be obtained and with what probabilities?
c) Calculate the expectation value of the total energy of the system.
d) Suppose that a measurement yields $4E_0$, write down the wave function immediately after the measurement.

> **Response**: For part a), we know $\Psi(x,t)$ is normalized if $\int_{-\infty}^{\infty}|\Psi(x,t)|^2dx = 1$. If we assume 
>
> $$\Psi(x,t) = \frac{1}{\sqrt{7}}\left(\sqrt{2}\chi_1(x)e^{-iE_1t/\hbar} + \sqrt{3}\chi_2(x)^{-iE_2t/\hbar} - i\chi_3(x)^{-iE_3t/\hbar} + \chi_4(x)^{-iE_4t/\hbar}\right)$$
>
> Then $\Psi(x,t)^*\Psi(x,t)$ will set all exponential terms to 1, and all we will have to worry about will be the coefficients, since the eigenstates form an orthonormal basis. Thus, we can prove $\Psi(x,t)$ is normalized by checking:
>
> $$\begin{align}\int_{-\infty}^{\infty}\Psi(x,t)^*\Psi(x,t) dx &= \frac{1}{7}\left(2 + 3 + 1 + 1\right) \\ &= 1\end{align}$$
>
> For part b), a measurment of energy gives one of the eigenvalues $E_n = n^2E_0$ with a probability $P = |c_n|^2$. Thus, the associated probabilities for each possible energy level is:
>
> $$\begin{align} n=1,\quad E_1 = E_0,\quad P = \frac{2}{7} \\ n=2,\quad E_2 = 4E_0,\quad P = \frac{3}{7} \\ n=3,\quad E_3 = 9E_0,\quad P = \frac{1}{7} \\ n=4,\quad E_4 = 16E_0, \quad P = \frac{1}{7} \end{align}$$
>
> For part c) the expectation value is given by:
>
> $$\begin{align}\left<E\right> &= \sum_n P(E_n)E_n \\ &= \frac{E_0}{7}\left(2\cdot1 + 3\cdot4 + 1\cdot9 + 1\cdot16\right) \\ &= \frac{39}{7}E_0\end{align}$$
>
> For part d), once a measurement is made, the wavefunction collapses and the only eigenstate that can exist is $\chi_2$, indicating a wave function of $$\psi(x) = \chi_2(x)$$ 



# Problem 3
The wave function for a particle of mass $m$ in a potential energy well for which $V=0$ for $0<x<L$ and $V=\infty$ elsewhere is given by $$\Psi(x) = \cases{\sqrt{\frac{105}{L^7}}x^2(L-x), \hspace{1cm} 0<x<L \\ 0, \hspace{3.3cm} \text{elsewhere.}}$$

What is the probability that a measurement of the energy of the particle yields the ground-state energy?

> **Response**: This problem can be solved easily with Mathematica. See [Problem 3 in the Mathematica file](2025FA_PHYS481_Assignment03_StJohn.pdf). 
>
> The probability that a measurement of the energy would return the value $E_n$ is given by 
>
> $$P(E_n) = |c_n|^2 = \left|\int_{-\infty}^{\infty}\psi_n(x)^*f(x)dx\right|^2$$
>
> In our case, $f(x)$ is the ground-state energy of the particle in an infinite square well, specifically
>
> $$f(x) = \sqrt{\frac{2}{L}}\sin\frac{pi n}{L}x$$
>
> where $n=0$. If we plug $f(x)$ and $\psi_n(x)$$ into our equation for $P(E_n)$, we get a probability of $$P=0.873736$$


# Problem 4
Find $\left<x\right>$, $\left<p\right>$, $\left<x^2\right>$, $\left<p^2\right>$, $\left<V\right>$ and $\left<T\right>$, for the nth stationary state of the harmonic oscillator, [use the method of Example 2.5 of textbook]. Check that the uncertainty principle is satisfied.

> **Response**: Using the method of Example 2.5 in the textbook, we can define $\hat{x}$ and $\hat{p}$ in terms of $\hat{a}_+$ and $\hat{a}_-$ to simplify integration.
>
> $$\hat{x} = \sqrt{\frac{\hbar}{2m\omega}}(\hat{a}_+ + \hat{a}_-),\quad \hat{p} = i\sqrt{\frac{\hbar m \omega}{2}}(\hat{a}_+ - \hat{a}_-)$$
>
> Also, a useful reminder:
>
> $$\hat{a}_+ \hat{a}_- \psi_n = n \psi_n,\quad \hat{a}_- \hat{a}_+ \psi_n = (n+1)\psi_n$$
>
> Beginning with $\left<x\right>$,
>
> $$\begin{align}\left<x\right> &= \int_{-\infty}^{\infty}\psi_n^*\hat{x}\psi_n dx \\ &= \sqrt{\frac{\hbar}{2m\omega}}\int_{-\infty}^{\infty}\psi_n^*(\hat{a}_+ + \hat{a}_-)\psi_n dx  \\ &= \sqrt{\frac{\hbar}{2m\omega}}\left(\int_{-\infty}^{\infty}\psi_n^*\hat{a}_+\psi_n dx + \int_{-\infty}^{\infty}\psi_n^*\hat{a}_-\psi_n dx\right) \\ &= \sqrt{\frac{\hbar}{2m\omega}}\left(\sqrt{n+1}\int_{-\infty}^{\infty}\psi_n^*\psi_{n+1} dx + \sqrt{n}\int_{-\infty}^{\infty}\psi_n^*\psi_{n-1} dx\right) \\ &= \sqrt{\frac{\hbar}{2m\omega}}\left(0 - 0\right) \\ &= 0\end{align}$$
>
> Similarly, for $\left<p\right>$,
>
> $$\left<p\right> = m\frac{d\left<x\right>}{dt} = 0$$
>
> However, $\left<x^2\right>$ is non-zero:
>
> $$\begin{align}\left<x^2\right> &= \int_{-\infty}^{\infty}\psi_n^*\hat{x}^2\psi_n dx \\ &= \frac{\hbar}{2m\omega}\int_{-\infty}^{\infty}\psi_n^*(\hat{a}_+^2 + \hat{a}_+\hat{a}_- + \hat{a}_-\hat{a}_+ + \hat{a}_-^2)\psi_n dx  \\ &= \frac{\hbar}{2m\omega}\left(\int_{-\infty}^{\infty}\psi_n^*\hat{a}_+\hat{a}_-\psi_n dx + \int_{-\infty}^{\infty}\psi_n^*\hat{a}_-\hat{a}_+\psi_n dx\right) \\ &= \frac{\hbar}{2m\omega}\left(n + (n+1)\right) \\ &= \frac{\hbar}{m\omega}\left(n+\frac{1}{2}\right)\end{align}$$
>
> Same goes for $\left<p^2\right>$:
> $$\begin{align}\left<p^2\right> &= \int_{-\infty}^{\infty}\psi_n^*\hat{p}^2\psi_n dx \\ &= -\frac{\hbar m \omega}{2}\int_{-\infty}^{\infty}\psi_n^*(\hat{a}_+^2 - \hat{a}_+\hat{a}_- - \hat{a}_-\hat{a}_+ + \hat{a}_-^2)\psi_n dx  \\ &= -\frac{\hbar m \omega}{2}\left(-\int_{-\infty}^{\infty}\psi_n^*\hat{a}_+\hat{a}_-\psi_n dx - \int_{-\infty}^{\infty}\psi_n^*\hat{a}_-\hat{a}_+\psi_n dx\right) \\ &= -\frac{\hbar m \omega}{2}\left(-n - (n+1)\right) \\ &= \frac{1}{2}\hbar m \omega\left(n+\frac{1}{2}\right)\end{align}$$
> 
> $\left<V\right>$ and $\left<T\right>$ are calulated as follows:
>
> $$\begin{align}\left<V\right> &= \left<\frac{1}{2}m\omega^2x^2\right> \\ &= \frac{1}{2}m\omega^2\left<x^2\right> \\ &= \frac{1}{2}m\omega^2\left(\frac{\hbar}{m\omega}\left(n+\frac{1}{2}\right)\right) \\ &= \frac{1}{2}\hbar\omega\left(n + \frac{1}{2}\right) \\ \\ \left<T\right> &= \left<\frac{p^2}{2m}\right> \\ &= \frac{\left<p^2\right>}{2m} \\ &= \frac{1}{2}\hbar\omega\left(n+ \frac{1}{2}\right)\end{align}$$
>
> Checking the uncertainty principle, we can see our results satisfy the condition.
>
> $$\begin{align} \sigma_x &= \sqrt{\left<x^2\right> - \left<x\right>^2} \\ &= \sqrt{\frac{\hbar}{m\omega}\left(n+\frac{1}{2}\right)} \\ \\ \sigma_p &= \sqrt{\left<p^2\right> - \left<p\right>^2} \\ &= \sqrt{\hbar m \omega\left(n+\frac{1}{2}\right)} \\ \\ \sigma_x\sigma_p &= \sqrt{\frac{\hbar}{m\omega}\left(n+\frac{1}{2}\right)} \sqrt{\hbar m \omega\left(n+\frac{1}{2}\right)} \\&= \hbar\left(n + \frac{1}{2}\right) \\ &\geq \frac{\hbar}{2}\end{align}$$


# Problem 5
In this problem we explore some of the more useful theorems (stated without proof) involving Hermite polynomials.

a) The **Rodrigues formula** says that $$H_n(\xi) = (-1)^n e^{\xi^2}\left(\frac{d}{d\xi}\right)^ne^{-\xi^2}$$ Use it to derive $H_3$ and $H_4$.
b) The following recursion relation gives you $H_{n+1}$ in terms of the two preceding Hermite polynomials: $$H_{n+1}(\xi)=2\xi H_n(\xi)-2nH_{n-1}(\xi).$$ Use it, together with your answer in (a), to obtain $H_5$ and $H_6$.
c) If you differentiate an $n$-th order polynomial, you get a polynomial of order $(n-1)$. For Hermite polynomials, in fact, $$\frac{dH_n}{d\xi}=2nH_{n-1}(\xi).$$ Check this, by differentiating $H_5$ and $H_6$.
d) $H_n(\xi)$ is the $n$-th $z$ derivative, at $z=0$, of the **generating function** $e^{-z^2 + 2z\xi}$; or to put it another way, it is the coefficient of $z^n/n!$ in the Taylor series expansion for this function: $$e^{-z^2 + 2z\xi} = \sum_{n=0}^{\infty}\frac{z^n}{n!}H_n(\xi)$$ Use this to obtain $H_1$, $H_2$ and $H_3$.

> **Response**: This problem was also solved with Mathematica. See [Problem 5 in the Mathematica file](2025FA_PHYS481_Assignment03_StJohn.pdf).